# Generated by Django 4.1 on 2022-09-01 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0002_ingredientes_pizza_delete_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.DateTimeField(auto_now=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tituto', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.pizza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
