# Generated by Django 4.1 on 2022-08-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='comentaios',
            new_name='comentarios',
        ),
    ]
