# Generated by Django 4.1 on 2022-08-20 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0002_rename_comentaios_pizza_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'pizzas'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='descricao',
            new_name='observacao',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.pizza'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='pizza.ingredientes'),
        ),
    ]
