# Generated by Django 4.1 on 2022-08-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_comentario_options_alter_pizza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'pizzas'},
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='descricao_pizza',
            field=models.TextField(blank=True),
        ),
    ]
